parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    displayName: Use Node
    inputs:
      versionSpec: 12.13.0
      checkLatest: true

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false

  - task: Gulp@0
    displayName: gulp compile
    inputs:
      targets: compile
      publishJUnitResults: true

  # - task: Npm@1
  #   displayName: npm test
  #   inputs:
  #     command: custom
  #     verbose: false
  #     customCommand: test
  #   continueOnError: true
  #   env:
  #     DISPLAY: ':99.0'

  - task: Gulp@0
    displayName: gulp lint
    inputs:
      targets: lint
