trigger:
  branches:
    include: ['*']

jobs:
- job: macOS
  timeoutInMinutes: 20
  pool:
    vmImage: 'macos-latest'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 16.14.2

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 16.14.2

- job: LinuxMinspec
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 16.14.2
    only_minspec: true

- job: Windows
  pool:
      vmImage: windows-latest
  steps:
  - template: common-validation.yml
  variables:
    node_version: 16.14.2
