trigger:
  branches:
    include: ['*']

jobs:
- job: macOS
  timeoutInMinutes: 20
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 12.13.0

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 12.13.0

- job: LinuxMinspec
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: common-validation.yml
  variables:
    node_version: 12.13.0
    only_minspec: true

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      # This step can be removed once Edge is included on the test VM image.
      # The download URI comes from: https://www.microsoftedgeinsider.com/en-us/download
      $InstallerDownloadURI = "https://go.microsoft.com/fwlink/?linkid=2084649&Channel=Canary&language=en&Consent=1"
      $InstallerExe = "$ENV:BUILD_ARTIFACTSTAGINGDIRECTORY\MicrosoftEdgeSetup.exe"
      Invoke-WebRequest -Uri $InstallerDownloadURI -OutFile $InstallerExe
      Start-Process $InstallerExe -Wait -ArgumentList '/silent /install'
      # Cleanup installer
      Remove-Item $InstallerExe
    displayName: Install Edge Canary
  - template: common-validation.yml
  variables:
    node_version: 12.13.0
