trigger:
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: tyler/allow-skipping-l10n
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    workingDirectory: dist
    publishExtension: ${{ parameters.publishExtension }}
    vscePackageArgs: --no-dependencies
    cgIgnoreDirectories: 'testdata,demos,.vscode-test'
    ghCreateRelease: true
    ghReleaseAddChangeLog: true
    l10nSkipProcessing: true
    buildSteps:
      - script: npm install
        displayName: Install dependencies

      - script: npm run compile -- package:prepare
        displayName: Package Stable
