trigger:
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false
  - name: publishGhRelease
    displayName: ☁️ Publish Github release
    type: boolean
    default: true

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    workingDirectory: dist
    publishExtension: ${{ parameters.publishExtension }}
    vscePackageArgs: --no-dependencies
    cgIgnoreDirectories: 'testdata,demos,.vscode-test'
    ${{ if eq(parameters.publishGhRelease, true) }}:
      ghCreateRelease: true
      ghReleaseAddChangeLog: true
    l10nSourcePaths: $(Build.SourcesDirectory)/src
    buildSteps:
      - script: npm install
        displayName: Install dependencies

      - script: npm run compile -- package:prepare
        displayName: Package Stable
