# Run on a schedule
trigger: none
pr: none

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: common-validation.yml
    parameters:
      runFrameworkTests: true

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: common-validation.yml
    parameters:
        runFrameworkTests: true

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: common-validation.yml
