/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/

const prettier = require('prettier');
const path = require('path');
const fs = require('fs');

function writeCodeToFile(code, relativeFilePath, prettierOpts = {}) {
  const fileName = path.join(__dirname, relativeFilePath);
  fs.writeFileSync(
    fileName,
    prettier.format(code, {
      parser: 'typescript',
      ...require('../package.json').prettier,
      ...prettierOpts,
    }),
    { encoding: 'utf-8' },
  );
}

function autoGeneratedFileHeader(autogenerationScriptName) {
  const result = [];
  result.push(`// Copyright (c) Microsoft Corporation.`);
  result.push(`// Licensed under the MIT license.`);
  result.push(``);
  result.push(`/****************************************************************`);
  result.push(` * Auto-generated by ${autogenerationScriptName}, do not edit manually. *`);
  result.push(` ****************************************************************/`);
  result.push(``);
  return result.join('\n');
}

module.exports = { writeCodeToFile, autoGeneratedFileHeader };
