name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validation:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            node_version: '22'
            only_minspec: false
          - name: Linux
            os: ubuntu-22.04
            node_version: '22'
            only_minspec: false
          - name: LinuxMinspec
            os: ubuntu-22.04
            node_version: '22'
            only_minspec: true
          - name: Windows
            os: windows-latest
            node_version: '22'
            only_minspec: false
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Start xvfb
        if: runner.os == 'Linux'
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      - name: npm install
        run: npm install --legacy-peer-deps

      - name: Test echo environment
        run: node -e "console.log(process.env.PATH)"
        env:
          JSDBG_TEST_VERSION: insiders
          DISPLAY: ':99.0'

      - name: npm test
        run: npm test
        timeout-minutes: 12
        env:
          JSDBG_TEST_VERSION: insiders
          JSDBG_USE_NODE_VERSION: ${{ matrix.node_version }}
          DISPLAY: ':99.0'

      - name: gulp lint
        if: ${{ !matrix.only_minspec }}
        run: npx gulp lint
